#include <windows.h>
#include <mmdeviceapi.h>
#include <audioclient.h>
#include <functiondiscoverykeys_devpkey.h>
#include <iostream>
#include <string>
#include <cmath>
#include <algorithm>
#pragma comment(lib,"ole32.lib")
static bool has(const std::wstring& a,const wchar_t* b){return a.find(b)!=std::wstring::npos;}
int wmain(){CoInitializeEx(nullptr,COINIT_MULTITHREADED);IMMDeviceEnumerator* en=nullptr;HRESULT hr=CoCreateInstance(__uuidof(MMDeviceEnumerator),nullptr,CLSCTX_ALL,IID_PPV_ARGS(&en));if(FAILED(hr)){std::wcerr<<L"enumerator failed\n";return 2;}IMMDeviceCollection* all=nullptr;hr=en->EnumAudioEndpoints(eCapture,DEVICE_STATE_ACTIVE,&all);if(FAILED(hr)){en->Release();return 2;}IMMDevice* target=nullptr;UINT n=0;all->GetCount(&n);for(UINT i=0;i<n;i++){IMMDevice* d=nullptr;IPropertyStore* ps=nullptr;PROPVARIANT v;PropVariantInit(&v);if(SUCCEEDED(all->Item(i,&d))&&SUCCEEDED(d->OpenPropertyStore(STGM_READ,&ps))&&SUCCEEDED(ps->GetValue(PKEY_Device_FriendlyName,&v))&&v.vt==VT_LPWSTR){std::wcout<<L"capture: "<<v.pwszVal<<L"\n";if(has(v.pwszVal,L"EchoDeck Combined Microphone"))target=d;else d->Release();}PropVariantClear(&v);if(ps)ps->Release();if(target)break;}all->Release();if(!target){std::wcerr<<L"EchoDeck Combined Microphone not found\n";en->Release();CoUninitialize();return 3;}IAudioClient* client=nullptr;IAudioCaptureClient* cap=nullptr;WAVEFORMATEX* fmt=nullptr;hr=target->Activate(__uuidof(IAudioClient),CLSCTX_ALL,nullptr,(void**)&client);if(SUCCEEDED(hr))hr=client->GetMixFormat(&fmt);if(SUCCEEDED(hr))hr=client->Initialize(AUDCLNT_SHAREMODE_SHARED,0,10000000,0,fmt,nullptr);if(SUCCEEDED(hr))hr=client->GetService(IID_PPV_ARGS(&cap));if(FAILED(hr)){std::wcerr<<L"endpoint cannot initialize\n";if(fmt)CoTaskMemFree(fmt);if(client)client->Release();target->Release();en->Release();CoUninitialize();return 4;}client->Start();ULONGLONG end=GetTickCount64()+3000;uint64_t frames=0;double sum=0;while(GetTickCount64()<end){UINT32 packets=0;if(SUCCEEDED(cap->GetNextPacketSize(&packets))&&packets){BYTE* data=nullptr;UINT32 f=0;DWORD flags=0;if(SUCCEEDED(cap->GetBuffer(&data,&f,&flags,nullptr,nullptr))){if(!(flags&AUDCLNT_BUFFERFLAGS_SILENT)){if(fmt->wBitsPerSample==32){float* p=(float*)data;for(UINT32 i=0;i<f*fmt->nChannels;i++)sum+=p[i]*p[i];}else if(fmt->wBitsPerSample==16){int16_t* p=(int16_t*)data;for(UINT32 i=0;i<f*fmt->nChannels;i++){double x=p[i]/32768.0;sum+=x*x;}}}frames+=f;cap->ReleaseBuffer(f);}}else Sleep(5);}client->Stop();double rms=frames?std::sqrt(sum/(double)(frames*fmt->nChannels)):0;std::wcout<<L"frames="<<frames<<L" sampleRate="<<fmt->nSamplesPerSec<<L" channels="<<fmt->nChannels<<L" rms="<<rms<<L"\n";int result=frames&&rms>0.00001?0:5;if(fmt)CoTaskMemFree(fmt);cap->Release();client->Release();target->Release();en->Release();CoUninitialize();return result;}
