#include "audio_engine.h"
#include <avrt.h>
#include <ksmedia.h>
#include <algorithm>
#include <cmath>
static std::wstring Hr(HRESULT h){wchar_t b[64];swprintf_s(b,L"HRESULT 0x%08X",(unsigned)h);return b;}
static bool IsFloat(const WAVEFORMATEX* f){if(f->wFormatTag==WAVE_FORMAT_IEEE_FLOAT)return true;if(f->wFormatTag==WAVE_FORMAT_EXTENSIBLE&&f->cbSize>=22){auto* e=(const WAVEFORMATEXTENSIBLE*)f;return IsEqualGUID(e->SubFormat,KSDATAFORMAT_SUBTYPE_IEEE_FLOAT);}return false;}
AudioEngine::~AudioEngine(){Stop();}
bool AudioEngine::OpenOutput(std::wstring& error){
 IMMDeviceEnumerator* en=nullptr;HRESULT hr=CoCreateInstance(__uuidof(MMDeviceEnumerator),nullptr,CLSCTX_ALL,IID_PPV_ARGS(&en));if(FAILED(hr)){error=Hr(hr);return false;}
 hr=en->GetDefaultAudioEndpoint(eRender,eConsole,&outDevice_);en->Release();if(FAILED(hr)){error=L"Saída padrão não encontrada";return false;}
 hr=outDevice_->Activate(__uuidof(IAudioClient),CLSCTX_ALL,nullptr,(void**)&outClient_);if(FAILED(hr)){error=Hr(hr);return false;}
 hr=outClient_->GetMixFormat(&format_);if(FAILED(hr)){error=Hr(hr);return false;}
 hr=outClient_->Initialize(AUDCLNT_SHAREMODE_SHARED,AUDCLNT_STREAMFLAGS_EVENTCALLBACK,10000000,0,format_,nullptr);if(FAILED(hr)){error=L"Não foi possível iniciar WASAPI: "+Hr(hr);return false;}
 hr=outClient_->GetBufferSize(&bufferFrames_);if(FAILED(hr)){error=Hr(hr);return false;}
 hr=outClient_->GetService(IID_PPV_ARGS(&render_));if(FAILED(hr)){error=Hr(hr);return false;}
 renderEvent_=CreateEventW(nullptr,FALSE,FALSE,nullptr);if(!renderEvent_){error=L"Não foi possível criar evento de áudio";return false;}
 hr=outClient_->SetEventHandle(renderEvent_);if(FAILED(hr)){error=Hr(hr);return false;}return true;
}
bool AudioEngine::OpenCapture(std::wstring& error){
 IMMDeviceEnumerator* en=nullptr;HRESULT hr=CoCreateInstance(__uuidof(MMDeviceEnumerator),nullptr,CLSCTX_ALL,IID_PPV_ARGS(&en));if(FAILED(hr)){error=Hr(hr);return false;}
 hr=en->GetDefaultAudioEndpoint(eCapture,eCommunications,&inDevice_);en->Release();if(FAILED(hr)){error=L"Microfone não encontrado";return false;}
 hr=inDevice_->Activate(__uuidof(IAudioClient),CLSCTX_ALL,nullptr,(void**)&inClient_);if(FAILED(hr)){error=Hr(hr);return false;}
 hr=inClient_->GetMixFormat(&captureFormat_);if(FAILED(hr)){error=Hr(hr);return false;}
 hr=inClient_->Initialize(AUDCLNT_SHAREMODE_SHARED,0,10000000,0,captureFormat_,nullptr);if(FAILED(hr)){error=L"Não foi possível abrir o microfone: "+Hr(hr);return false;}
 hr=inClient_->GetService(IID_PPV_ARGS(&capture_));if(FAILED(hr)){error=Hr(hr);return false;}return true;
}
bool AudioEngine::Start(std::wstring& error){if(running_)return true;CoInitializeEx(nullptr,COINIT_MULTITHREADED);if(!OpenOutput(error)||!OpenCapture(error)){ReleaseAudio();CoUninitialize();return false;}bridgeChannels_=std::min<uint32_t>(format_->nChannels,ECHODECK_MAX_CHANNELS);std::wstring bridgeError;bridgeReady_=bridge_.Open(format_->nSamplesPerSec,bridgeChannels_,bridgeError);running_=true;HRESULT hr=outClient_->Start();if(FAILED(hr)){error=Hr(hr);running_=false;bridge_.Close();ReleaseAudio();CoUninitialize();return false;}hr=inClient_->Start();if(FAILED(hr)){error=Hr(hr);running_=false;bridge_.Close();ReleaseAudio();CoUninitialize();return false;}renderThread_=std::thread(&AudioEngine::RenderLoop,this);captureThread_=std::thread(&AudioEngine::CaptureLoop,this);return true;}
void AudioEngine::Stop(){if(!running_.exchange(false))return;if(renderEvent_)SetEvent(renderEvent_);if(renderThread_.joinable())renderThread_.join();if(captureThread_.joinable())captureThread_.join();if(outClient_)outClient_->Stop();if(inClient_)inClient_->Stop();bridge_.Close();bridgeReady_=false;ReleaseAudio();CoUninitialize();}
void AudioEngine::ReleaseAudio(){std::lock_guard<std::mutex> l(voicesMutex_);voices_.clear();if(render_)render_->Release();if(outClient_)outClient_->Release();if(outDevice_)outDevice_->Release();if(capture_)capture_->Release();if(inClient_)inClient_->Release();if(inDevice_)inDevice_->Release();if(renderEvent_)CloseHandle(renderEvent_);if(format_)CoTaskMemFree(format_);if(captureFormat_)CoTaskMemFree(captureFormat_);render_=nullptr;outClient_=nullptr;outDevice_=nullptr;capture_=nullptr;inClient_=nullptr;inDevice_=nullptr;renderEvent_=nullptr;format_=nullptr;captureFormat_=nullptr;}
bool AudioEngine::Play(const WavFile& sound,float volume,bool loop,std::wstring& error){if(!running_){error=L"Audio Engine parado";return false;}if(sound.channels==0||sound.samples.empty()){error=L"Som vazio";return false;}std::lock_guard<std::mutex> l(voicesMutex_);voices_.push_back({sound,0,volume,loop});return true;}
void AudioEngine::StopAll(){std::lock_guard<std::mutex> l(voicesMutex_);voices_.clear();}
void AudioEngine::RenderLoop(){const bool outFloat=IsFloat(format_);const int outCh=format_->nChannels;const int outRate=format_->nSamplesPerSec;std::vector<float> bridgeFrames;while(running_){DWORD w=WaitForSingleObject(renderEvent_,100);if(w==WAIT_TIMEOUT)continue;UINT32 pad=0;if(FAILED(outClient_->GetCurrentPadding(&pad)))continue;UINT32 frames=bufferFrames_-pad;BYTE* data=nullptr;if(!frames||FAILED(render_->GetBuffer(frames,&data)))continue;std::fill(data,data+frames*format_->nBlockAlign,0);{
  std::lock_guard<std::mutex> l(voicesMutex_);for(auto it=voices_.begin();it!=voices_.end();){Voice& v=*it;size_t srcFrames=v.sound.samples.size()/v.sound.channels;for(UINT32 f=0;f<frames;f++){if(v.position>=srcFrames){if(v.loop)v.position=0;else break;}if(v.position>=srcFrames)break;size_t sourceFrame=(size_t)v.position;for(int c=0;c<outCh;c++){int sc=std::min(c,(int)v.sound.channels-1);size_t si=sourceFrame*v.sound.channels+sc;float add=v.sound.samples[si]*v.volume*master_.load();if(outFloat)((float*)data)[f*outCh+c]+=add;else{int16_t* q=(int16_t*)data;int val=(int)std::lround(std::clamp(add,-1.f,1.f)*32767);int pos=f*outCh+c;q[pos]=(int16_t)std::clamp((int)q[pos]+val,-32768,32767);}}v.position+=(double)v.sound.sampleRate/outRate;}if(!v.loop&&v.position>=srcFrames)it=voices_.erase(it);else ++it;}}
  if(bridgeReady_){bridgeFrames.assign((size_t)frames*bridgeChannels_,0.f);{std::lock_guard<std::mutex> ml(micMutex_);for(UINT32 f=0;f<frames;f++){float mic=micSamples_.empty()?0.f:micSamples_.front();if(!micSamples_.empty())micSamples_.pop_front();for(uint32_t c=0;c<bridgeChannels_;c++){float speaker=outFloat?((float*)data)[f*outCh+std::min<int>(c,outCh-1)]:((int16_t*)data)[f*outCh+std::min<int>(c,outCh-1)]/32768.f;bridgeFrames[f*bridgeChannels_+c]=std::clamp(speaker+mic*0.7f,-1.f,1.f);}}}bridge_.Write(bridgeFrames.data(),frames);}
 render_->ReleaseBuffer(frames,0);}}
void AudioEngine::CaptureLoop(){const UINT32 bytesPerSample=captureFormat_?captureFormat_->wBitsPerSample/8:2;while(running_){UINT32 packets=0;if(FAILED(capture_->GetNextPacketSize(&packets))){Sleep(10);continue;}while(packets){BYTE* data=nullptr;UINT32 frames=0;DWORD flags=0;if(FAILED(capture_->GetBuffer(&data,&frames,&flags,nullptr,nullptr)))break;if(!(flags&AUDCLNT_BUFFERFLAGS_SILENT)&&frames){double sum=0;int ch=std::max<int>(1,captureFormat_->nChannels);std::lock_guard<std::mutex> ml(micMutex_);for(UINT32 i=0;i<frames;i++){float avg=0;for(int c=0;c<ch;c++){float x=0;if(bytesPerSample==2)x=((int16_t*)data)[i*ch+c]/32768.f;else if(bytesPerSample==4)x=((float*)data)[i*ch+c];avg+=x;sum+=x*x;}avg/=ch;micSamples_.push_back(avg);}while(micSamples_.size()>32768)micSamples_.pop_front();micLevel_=std::min(1.f,(float)(std::sqrt(sum/(frames*ch))*3.0));}capture_->ReleaseBuffer(frames);if(FAILED(capture_->GetNextPacketSize(&packets)))break;}Sleep(3);}}
