#include <windows.h>
#include <commctrl.h>
#include <commdlg.h>
#include <string>
#include <vector>
#include <fstream>
#include <iomanip>
#include <shlobj.h>
#include "audio_engine.h"
#include "device_utils.h"
#pragma comment(lib,"comctl32.lib")
struct Item { std::wstring name,path; WavFile wav; bool loaded=false; float volume=1.f; };
struct App { HWND hwnd{},status{},meter{},list{},volume{}; AudioEngine engine; std::vector<Item> items; };
static App* app=nullptr;
static std::wstring LibraryPath(){wchar_t dir[MAX_PATH]{};if(FAILED(SHGetFolderPathW(nullptr,CSIDL_APPDATA,nullptr,SHGFP_TYPE_CURRENT,dir)))return L"EchoDeck-library.txt";std::wstring d=std::wstring(dir)+L"\\EchoDeck";CreateDirectoryW(d.c_str(),nullptr);return d+L"\\library.txt";}
static void LoadSoundLibrary(){std::wifstream f;std::wstring file=LibraryPath();f.open(file.c_str());if(!f)return;std::wstring path,name;float volume;while(f>>std::quoted(path)>>std::quoted(name)>>volume)app->items.push_back({name,path,{},false,volume});}
static void SaveSoundLibrary(){std::wofstream f;std::wstring file=LibraryPath();f.open(file.c_str(),std::ios::trunc);for(const auto& x:app->items)f<<std::quoted(x.path)<<L" "<<std::quoted(x.name)<<L" "<<x.volume<<L"\n";}
static void Text(HWND h,const std::wstring& s){SetWindowTextW(h,s.c_str());}
static HWND Btn(HWND p,const wchar_t* s,int id,int x,int y,int w=170,int h=32){return CreateWindowW(L"BUTTON",s,WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,x,y,w,h,p,(HMENU)(INT_PTR)id,GetModuleHandleW(nullptr),nullptr);}
static void ShowDevices(){std::wstring s=L"INPUT DEVICES\r\n"+EnumerateAudioDevices(true)+L"\r\nOUTPUT DEVICES\r\n"+EnumerateAudioDevices(false);MessageBoxW(app->hwnd,s.c_str(),L"EchoDeck Audio Devices",MB_OK|MB_ICONINFORMATION);}
static void ShowDiagnostics(){std::wstring s=L"EchoDeck Audio Diagnostics\r\n\r\nWASAPI: "+std::wstring(app->engine.Running()?L"running":L"stopped")+L"\r\nRing bridge: "+std::wstring(app->engine.BridgeReady()?L"ready":L"unavailable")+L"\r\nMicrophone level: "+std::to_wstring((int)(app->engine.MicLevel()*100))+L"%\r\n\r\nINPUT\r\n"+EnumerateAudioDevices(true)+L"\r\nOUTPUT\r\n"+EnumerateAudioDevices(false);MessageBoxW(app->hwnd,s.c_str(),L"Audio Diagnostics",MB_OK|MB_ICONINFORMATION);}
static void RefreshList(){if(!app)return;DestroyWindow(app->list);app->list=CreateWindowW(L"STATIC",L"",WS_CHILD|WS_VISIBLE,20,120,730,430,app->hwnd,nullptr,GetModuleHandleW(nullptr),nullptr);int y=8;for(size_t i=0;i<app->items.size();i++){std::wstring label=L"▶ "+app->items[i].name;Btn(app->list,label.c_str(),1000+(int)i,8,y,490,32);HWND slider=CreateWindowW(TRACKBAR_CLASSW,L"",WS_CHILD|WS_VISIBLE|TBS_AUTOTICKS,510,y+3,175,26,app->list,(HMENU)(INT_PTR)(2000+(int)i),GetModuleHandleW(nullptr),nullptr);SendMessageW(slider,TBM_SETRANGE,TRUE,MAKELONG(0,100));SendMessageW(slider,TBM_SETPOS,TRUE,(LPARAM)(app->items[i].volume*100));y+=42;}}
static void Import(){wchar_t file[32768]{};OPENFILENAMEW ofn{sizeof(ofn)};ofn.hwndOwner=app->hwnd;ofn.lpstrFile=file;ofn.nMaxFile=32768;ofn.lpstrFilter=L"WAV PCM (*.wav)\0*.wav\0Todos os arquivos\0*.*\0";ofn.Flags=OFN_ALLOWMULTISELECT|OFN_EXPLORER|OFN_FILEMUSTEXIST;if(!GetOpenFileNameW(&ofn))return;std::wstring first=file;wchar_t* p=file+first.size()+1;if(*p==0){app->items.push_back({first.substr(first.find_last_of(L"\\/")+1),first,{}});}else{std::wstring dir=first;while(*p){std::wstring n=p;app->items.push_back({n,dir+L"\\"+n,{}});p+=n.size()+1;}}SaveSoundLibrary();RefreshList();Text(app->status,L"Arquivos importados. WAV PCM 16-bit pronto para tocar.");}
static void Play(size_t i){if(i>=app->items.size())return;auto& x=app->items[i];if(!x.loaded){std::wstring e;if(!LoadWav(x.path,x.wav,e)){Text(app->status,L"Falha: "+e);return;}x.loaded=true;}std::wstring e;if(!app->engine.Play(x.wav,x.volume,false,e))Text(app->status,L"Falha ao reproduzir: "+e);}
static LRESULT CALLBACK Proc(HWND h,UINT m,WPARAM w,LPARAM l){switch(m){case WM_CREATE:{app=new App();app->hwnd=h;app->status=CreateWindowW(L"STATIC",L"Iniciando EchoDeck Audio Engine...",WS_CHILD|WS_VISIBLE,20,16,730,24,h,nullptr,GetModuleHandleW(nullptr),nullptr);app->meter=CreateWindowW(L"STATIC",L"MIC 0%",WS_CHILD|WS_VISIBLE,20,45,180,24,h,nullptr,GetModuleHandleW(nullptr),nullptr);Btn(h,L"＋ Importar WAV",1,20,78,150);Btn(h,L"■ Parar tudo",2,180,78,135);Btn(h,L"Audio Devices",4,325,78,130);Btn(h,L"Diagnostics",5,465,78,130);CreateWindowW(L"STATIC",L"MASTER",WS_CHILD|WS_VISIBLE,610,48,55,20,h,nullptr,GetModuleHandleW(nullptr),nullptr);app->volume=CreateWindowW(TRACKBAR_CLASSW,L"",WS_CHILD|WS_VISIBLE|TBS_AUTOTICKS,665,42,105,28,h,(HMENU)3,GetModuleHandleW(nullptr),nullptr);SendMessageW(app->volume,TBM_SETRANGE,TRUE,MAKELONG(0,100));SendMessageW(app->volume,TBM_SETPOS,TRUE,100);for(int i=0;i<9;i++)RegisterHotKey(h,500+i,MOD_CONTROL|MOD_ALT,'1'+i);LoadSoundLibrary();RefreshList();std::wstring e;if(app->engine.Start(e))Text(app->status,app->engine.BridgeReady()?L"LIMITED • WASAPI + ring bridge ativo; WDK separado":L"LIMITED • WASAPI ativo; WDK não instalado");else Text(app->status,L"ERROR • engine: "+e);SetTimer(h,77,100,nullptr);return 0;}case WM_COMMAND:{int id=LOWORD(w);if(id==1)Import();else if(id==2)app->engine.StopAll();else if(id==4)ShowDevices();else if(id==5)ShowDiagnostics();else if(id>=1000&&id<2000)Play(id-1000);return 0;}case WM_HOTKEY:if(w>=500&&w<509)Play(w-500);return 0;case WM_TIMER:if(w==77){wchar_t b[80];swprintf_s(b,L"MIC %d%%",(int)(app->engine.MicLevel()*100));Text(app->meter,b);}return 0;case WM_HSCROLL:{HWND source=(HWND)l;if(source==app->volume){app->engine.SetMaster(SendMessageW(app->volume,TBM_GETPOS,0,0)/100.f);}else{int id=GetDlgCtrlID(source);if(id>=2000&&id<3000){int i=id-2000;if((size_t)i<app->items.size()){app->items[i].volume=SendMessageW(source,TBM_GETPOS,0,0)/100.f;SaveSoundLibrary();}}return 0;}}case WM_DESTROY:KillTimer(h,77);for(int i=0;i<9;i++)UnregisterHotKey(h,500+i);if(app){app->engine.Stop();delete app;app=nullptr;}PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,w,l);}
int WINAPI wWinMain(HINSTANCE hi,HINSTANCE, PWSTR,int show){INITCOMMONCONTROLSEX ic{sizeof(ic),ICC_BAR_CLASSES};InitCommonControlsEx(&ic);WNDCLASSW wc{};wc.hInstance=hi;wc.lpfnWndProc=Proc;wc.lpszClassName=L"EchoDeckNative";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassW(&wc);HWND h=CreateWindowW(wc.lpszClassName,L"EchoDeck — Audio Assistant",WS_OVERLAPPEDWINDOW,100,100,800,600,nullptr,nullptr,hi,nullptr);ShowWindow(h,show);UpdateWindow(h);MSG msg;while(GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}return (int)msg.wParam;}
